import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import CustomH2 from "@/components/CustomH2";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>あああ</h1>
        <article>
          <CustomH2>カスタムh2</CustomH2>
        </article>

    <div>
          <section>
            <h3>aaa</h3>
          </section>
    </div>
      </main>
    </>
  );
}
